### ISSUE TITLE
Can we add the Hacktoberfest tag to the repository?

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang.org#16]
If you complete the challenge you can choose to plant a tree in your name or you can get a tshirt.

There are two ways to participate: as a maintainer or as a contributor.

Maintainer has to add the tag hacktoberfest to the repo or apply tag hacktoberfest-accepted to the PR and merge 5 PRs.

Contributors have to submit 5 PRs which get merged in this month.

**Comment by jenshaase** [comment]
Let's discuss this in here: https://github.com/phel-lang/phel-lang/issues/372
