### ISSUE TITLE
In Getting Started, pls. show how to call compiled code via index.php

### ISSUE THREAD

**Issue by kloimhardt** [phel-lang/phel-lang.org#18]
The "Running the Code" section of the "hello-world" example describes how to create an index.php that runs the code via the Phel Runtime. Is it possible to add an index.php example that shows how to call the code generated with the new "compile" command?

**Comment by Chemaclass** [comment]
Hi, @kloimhardt!
Did you check out our `phel-scaffolding` project? There you can find an example of how to run phel code from your `index.php`: https://github.com/phel-lang/phel-scaffolding/blob/master/example/using-exported-phel-function.php Is this what you were looking for?
> You can run it simply with `php example/using-exported-phel-function.php`
<img width="807" alt="Screenshot 2021-12-22 at 20 12 46" src="https://user-images.githubusercontent.com/5256287/147143543-94e97c57-eb3a-4a87-bdd9-eeac153f1345.png">

**Comment by jenshaase** [comment]
@Chemaclass This is not what @kloimhardt is asking for. But he is right that we miss some information there. 

With the compile command we have the possibility to remove the `index.php` file. What you can do is to compile the `src/boot.phel` file of the getting started guide and then run the php server directly on the compiled file (`php -S localhost:8000 ./out/hello-world/boot.php`). However, this has currently some drawbacks. First, you need to load the `vendor/autoload.php` file and secondly every time you change the code you have to run the compile command again.

The first problem can be solved by adding `(php/require "vendor/autoload.php")` to the `src/boot.phel` file (You may have to adopt the path depending on the output directory of the compile command).
With tools like entr (https://eradman.com/entrproject/) you could solve the second problem for now.

**Comment by Chemaclass** [comment]
Actually... is there any doc in the website related to the compiler command, I don't see any? 🤔

**Comment by kloimhardt** [comment]
Thank you for the immediate response. However, I am doing something wrong:

```
~/temp/hello-world$ vendor/bin/phel run src/boot.phel
Hello, World!
~/temp/hello-world$ vendor/bin/phel compile
Hello, World!
~/temp/hello-world$ php -S localhost:8000 ./out/hello-world/boot.php
[Wed Dec 22 21:30:14 2021] PHP 7.4.27 Development Server (http://localhost:8000) started
[Wed Dec 22 21:30:22 2021] [::1]:49962 Accepted
[Wed Dec 22 21:30:22 2021] PHP Warning:  require_once(/Users/kloimhardt/temp/hello-world/out/hello-world/../../phel/core.php): failed to open stream: No such file or directory in /Users/kloimhardt/temp/hello-world/out/hello-world/boot.php on line 3
[Wed Dec 22 21:30:22 2021] PHP Fatal error:  require_once(): Failed opening required '/Users/kloimhardt/temp/hello-world/out/hello-world/../../phel/core.php' (include_path='.:/usr/local/Cellar/php@7.4/7.4.27/share/php@7.4/pear') in /Users/kloimhardt/temp/hello-world/out/hello-world/boot.php on line 3
[Wed Dec 22 21:30:22 2021] [::1]:49962 Closing
```

**Comment by kloimhardt** [comment]
When I do
```
$ vendor/bin/phel compile
$ localhost:8000 ./out/hello-world/boot.php
```
I get
```
[Wed Dec 22 21:40:38 2021] PHP 7.4.27 Development Server (http://localhost:8000) started
[Wed Dec 22 21:40:43 2021] [::1]:49967 Accepted
[Wed Dec 22 21:40:43 2021] PHP Warning:  require_once(/Users/kloimhardt/temp/hello-world/out/hello-world/../../phel/core.php): failed to open stream: No such file or directory in /Users/kloimhardt/temp/hello-world/out/hello-world/boot.php on line 3
```

**Comment by jenshaase** [comment]
Hi @kloimhardt,

I took a deeper look now. Actually there was an error in the compile command. I fixed it with the [this commit](https://github.com/phel-lang/phel-lang/commit/0cb884bf2a2fc1dffc8a4b65c0aafcfc9b155e7b). If you want you can update your composer.json with the following requirement to use it before I release a new version.

```
"require": {
  "phel-lang/phel-lang": "v0.5.x-dev"
}
```

Additionally, the proposed `(php/require "vendor/autoload.php")` is not really working because it is loaded to late. I need to find a better way do deal with this problem. For now I recommend to create a `index.php` like this:

```php
<?php

use Phel\Compiler\Analyzer\Environment\GlobalEnvironmentSingleton;

require_once __DIR__ . "/vendor/autoload.php";
GlobalEnvironmentSingleton::initialize(); // I try to ride of this line in a later release. 
require_once __DIR__ . "/out/hello-world/boot.php";
```

and then run the PHP server `php -S localhost:8080 index.php`

If you want to follow the process you can subscribe to the issues: https://github.com/phel-lang/phel-lang/issues/408 and https://github.com/phel-lang/phel-lang/issues/409

**Comment by kloimhardt** [comment]
@jenshaase thank you! Compile works for "hello-world" now. I can close this issue.

I do not know what the scope of compile really is and what it is meant to be for, so I just leave the following as an ifo which might or might not be interesting/helpful:
 
I tried to compile the otherwise working [lisp-webscript-examples](https://github.com/kloimhardt/lisp-webscript-examples), but it throws some errors:

```
In CompiledCodeIsMalformedException.php line 14:
  cannot determine HTTP Method  
                                
In __phelOWV6fE line 25:
  cannot determine HTTP Method 
```

**Comment by jenshaase** [comment]
I created a PR to solve this problem: https://github.com/kloimhardt/lisp-webscript-examples/pull/4
