### ISSUE TITLE
Implement TOC

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang.org#19]
Since the documentation gets bigger it gets more difficult to navigate it.

**Comment by Chemaclass** [comment]
Do you mean a Table of Content, right? Isn't this what you're looking for? https://phel-lang.org/documentation/api/ 
Or what do you have in mind? 🤔

**Comment by mabasic** [comment]
![Web capture_28-12-2021_0199_laravel com](https://user-images.githubusercontent.com/1839930/147513145-a0b459b9-2a6f-4187-8b10-4678325299ce.jpeg)

For each documentation section a table of content so that it is easier to see what is inside each section.

**Comment by Chemaclass** [comment]
Great idea! I will work on this.
