### ISSUE TITLE
Add next/previous links to the blog

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang.org#33]
## Description

We recently introduced a blog section in the website. The blog posts are nice, but it would be better if you could navigate to the next/previous one from one single post-entry.

## Acceptance Criteria

Add at the Botton of a bog-entry two links, one to go to the previous and to the next blog entry.

> Check this example out: https://github.com/Chemaclass/chemaclass.es/blob/master/templates/blog/blog-post.html#L31

**Comment by jenshaase** [comment]
Accomplished in #35
