### ISSUE TITLE
Host the website in netlify to use the CD

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang.org#6]
## Why?

To be able to deploy automatically right after pushing new changes to `master`. **Continuous Delivery**

## How?

You can see how here: https://www.getzola.org/documentation/deployment/netlify/

You can easily set up a continuous deployment in [netlify](https://app.netlify.com/). 

### Personal website
I already managed to do the whole thing with my new [website](https://github.com/Chemaclass/chemaclass.es), which I also build using Zola. It's easy and free for OSS and simple webs such as docu or personal blogs.

<img width="615" alt="Screenshot 2021-06-13 at 21 14 56" src="https://user-images.githubusercontent.com/5256287/121819267-695b2200-cc8c-11eb-9c37-fa1ae0941990.png">

### Gacela

I also hosted http://gacela-project.com/ there as well, which uses `npm` to build the JS. Just to show you another example that doesn't use Zola.

<img width="604" alt="Screenshot 2021-06-13 at 21 21 38" src="https://user-images.githubusercontent.com/5256287/121819432-59900d80-cc8d-11eb-943b-7556c178be09.png">

**Comment by jenshaase** [comment]
It is not deployed on netlify, but I integrated an auto deployment.

**Comment by Chemaclass** [comment]
Totally fine for me! I thought Netlify would be the easiest, but the real goal was automatic deployment after pushing.
