### ISSUE TITLE
Is there any documentation about Error Handling?

### ISSUE THREAD

**Issue by smeghead** [phel-lang/phel-lang.org#73]
I really enjoy programming with phel-lang. thank you.

There was a situation where I wanted to perform error handling in phel-lang, and I checked the documentation, but there was no mention of it.
https://phel-lang.org/documentation/getting-started/

When I looked at the source code of phel-lang, I found that it uses try/catch similar to clojure.
Is there a reason why there is no mention of error handling in the documentation?

**Comment by Chemaclass** [comment]
Hi, @smeghead ! we have documented the try/catch here [documentation/control-flow/#try-catch-and-finally](https://phel-lang.org/documentation/control-flow/#try-catch-and-finally)

**Comment by smeghead** [comment]
Hi, @Chemaclass 
thank you.
I just couldn't find what was mentioned in Control flow.
