### ISSUE TITLE
Add examples for Apache and Ngnix

### ISSUE THREAD

**Issue by WilsonSant** [phel-lang/phel-lang.org#75]
_A little bit of self promotion 😆_ 
 I think it would be a great idea to have examples on the project's website running on these servers. I had a bit of difficulty, but I managed to run Phel with Apache:
https://github.com/WilsonSant/Phel-Apache

**Comment by Chemaclass** [comment]
hi, @WilsonSant , we already have a [web-skeleton](https://github.com/phel-lang/web-skeleton), I think it's pretty similar, isn't it? :)

**Comment by WilsonSant** [comment]
Agreed
