### ISSUE TITLE
Document accessing superglobals directly

### ISSUE THREAD

**Issue by jasalt** [phel-lang/phel-lang.org#90]
Found a possible gap in the docs while figuring out how to connect to WordPress (MySQL) database from Phel which requires accessing the [wpdb](https://developer.wordpress.org/reference/classes/wpdb/#using-the-wpdb-global-object) object via [PHP superglobals](https://docs.phplang.net/en/language.variables.superglobals.php).

I was looking for something equivalent to the PHP `global` statement first ([generally recommended with wpdb](https://developer.wordpress.org/reference/classes/wpdb/#using-the-wpdb-global-object)), but the alternative method by accessing `$GLOBALS` superglobals array seemed more feasible. 

Figured to access the $GLOBALS array then with `(get php/$GLOBALS "wpdb")` after reading Phel http library [sources](https://github.com/phel-lang/phel-lang/blob/993d2293441787b470ae3ea4f293e978f0c93991/src/phel/http.phel#L56) that I knew to be messing with the superglobals.

Docs didn't really give any good pointers about this so maybe it could be worth to mention something about it in eg. "[Global and local bindings](https://phel-lang.org/documentation/global-and-local-bindings/)" or "[PHP interop](https://phel-lang.org/documentation/php-interop/)" or both as they'd seem the most logical places, if this would be considered a general enough issue? I'm not very familiar with the PHP ecosystem at large but find this somewhat frequent related to WP at least.

**Comment by Chemaclass** [comment]
Would this be enough, @jasalt ? Or you would like to have something else?

![Screenshot 2024-11-29 at 18 39 32](https://github.com/user-attachments/assets/4f1326e4-da31-4281-b989-7ca9139346bf)

**Comment by jasalt** [comment]
@Chemaclass Yes, it's a good hint now as is. I'll add new suggestions when I find other useful things to document.
